export const errorTypes = {
  NEW_ERROR: 'ERRORS/NEW_ERROR',
};

export const sessionTypes = {
  LOGIN_REQUEST: 'SESSION/LOGIN_REQUEST',
  SIGNUP_REQUEST: 'SESSION/SIGNUP_REQUEST',
  LOGOUT: 'SESSION/LOGOUT',
  AUTHENTICATION_REQUEST: 'SESSION/AUTHENTICATION_REQUEST',
  AUTHENTICATION_SUCCESS: 'SESSION/AUTHENTICATION_SUCCESS',
  AUTHENTICATION_FAILURE: 'SESSION/AUTHENTICATION_FAILURE',
  CONNECT: 'SESSION/CONNECT',
  CONNECT_REQUEST: 'SESSION/CONNECT_REQUEST',
  CONNECT_SUCCESS: 'SESSION/CONNECT_SUCCESS',
  CONNECT_FAILURE: 'SESSION/CONNECT_FAILURE',
};
